"""
EVILISM Discord Verification Bot
bot.py — Main bot entry point

Handles:
  • Assigning "The Uninitiated" role when a new member joins
  • Ghost-pinging the new member in #verification-portal
  • Sending an ephemeral (user-only) message with the verification link
  • Listening in #verification-portal for key redemptions
  • Promoting accepted members / assigning Sacrificial Lambs on denial/expiry
"""

import discord
from discord.ext import commands, tasks
import asyncio
import logging
from config import Config
from database import Database

# ── Logging ──────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("evilism.bot")

# ── Intents ──────────────────────────────────────────────────
intents = discord.Intents.default()
intents.members  = True   # Required for on_member_join
intents.message_content = True  # Required to read messages in portal

bot = commands.Bot(command_prefix="!", intents=intents)
db  = Database()


# ════════════════════════════════════════════════════════════
#  READY
# ════════════════════════════════════════════════════════════
@bot.event
async def on_ready():
    log.info(f"EVILISM bot online as {bot.user} (ID: {bot.user.id})")
    # Sync globally
    try:
        synced = await bot.tree.sync()
        log.info(f"Synced {len(synced)} slash commands globally.")
    except Exception as e:
        log.error(f"Failed to sync slash commands: {e}")
    
    if not check_expiries.is_running():
        check_expiries.start()
    log.info("Expiry checker started.")

@bot.command()
@commands.is_owner()
async def sync(ctx):
    """Manual sync command for the bot owner."""
    try:
        synced = await bot.tree.sync()
        await ctx.send(f"Successfully synced {len(synced)} commands.")
    except Exception as e:
        await ctx.send(f"Failed to sync: {e}")


# ════════════════════════════════════════════════════════════
#  NEW MEMBER JOINS
# ════════════════════════════════════════════════════════════
@bot.event
async def on_member_join(member: discord.Member):
    guild = member.guild
    log.info(f"New member joined: {member} ({member.id})")

    # 1. Assign "The Uninitiated" role
    uninitiated_role = discord.utils.get(guild.roles, name=Config.ROLE_UNINITIATED)
    if uninitiated_role:
        try:
            await member.add_roles(uninitiated_role, reason="New member — awaiting verification")
            log.info(f"Assigned '{Config.ROLE_UNINITIATED}' to {member}")
        except discord.Forbidden:
            log.warning(f"Missing permissions to assign role to {member}")
    else:
        log.warning(f"Role '{Config.ROLE_UNINITIATED}' not found in guild.")

    # 2. Ghost-ping in #verification-portal
    portal_channel = discord.utils.get(guild.text_channels, name=Config.CHANNEL_VERIFICATION_PORTAL)
    if portal_channel:
        ghost = await portal_channel.send(member.mention)
        await ghost.delete()
        log.info(f"Ghost-pinged {member} in #{Config.CHANNEL_VERIFICATION_PORTAL}")
    else:
        log.warning(f"Channel '{Config.CHANNEL_VERIFICATION_PORTAL}' not found.")
        return

    # 3. Send ephemeral-style message via DM (Discord ephemeral only works with interactions)
    #    We send a DM from the bot — this is the "message only you can see" equivalent.
    verification_url = f"{Config.GITHUB_PAGES_URL}?token=PENDING"
    # The real token is generated by the backend on OAuth callback.
    # We send the GitHub Pages URL; the user logs in via Discord there.

    dm_message = (
        f"**Welcome to EVILISM, {member.display_name}.**\n\n"
        f"You have arrived at the Gates of Umbra. Before you may walk among us, "
        f"you must prove your worth and your loyalty.\n\n"
        f"**Your next step:** Complete the Initiate Application Form.\n"
        f">>> {Config.GITHUB_PAGES_URL}\n\n"
        f"**Before you begin, understand the following:**\n"
        f"— You will be required to log in with Discord on the form. This is how we confirm who you are.\n"
        f"— Your answers will be reviewed directly by **The Dark Council** or **UMBRA**.\n"
        f"— The form expires in **7 days**. If it expires before a decision is made, "
        f"your entry is automatically denied and you must submit again from the beginning.\n"
        f"— Once submitted, **you cannot resubmit**. Choose your words carefully.\n"
        f"— If accepted, you will receive a **verification key** here via DM. "
        f"That key expires in **3.5 days (84 hours)**. Paste it into "
        f"<#{await _get_portal_channel_id(guild)}> to complete your initiation.\n"
        f"— If your key expires before you use it, you will be assigned a temporary "
        f"restricted role and must reapply.\n\n"
        f"**Do not dismiss this message.** The link above is your only path forward.\n\n"
        f"*The Cult is watching. Do not keep us waiting.*\n"
        f"— **EVILISM Verification System**"
    )

    try:
        await member.send(dm_message)
        log.info(f"Sent verification DM to {member}")
    except discord.Forbidden:
        # User has DMs disabled — post in portal as a fallback mention
        if portal_channel:
            fallback = await portal_channel.send(
                f"{member.mention} — I tried to send you a DM but your privacy settings blocked it. "
                f"Please enable DMs from server members so I can send you your verification link.",
                delete_after=120,
            )
        log.warning(f"Could not DM {member} — DMs likely disabled.")


async def _get_portal_channel_id(guild: discord.Guild) -> int:
    ch = discord.utils.get(guild.text_channels, name=Config.CHANNEL_VERIFICATION_PORTAL)
    return ch.id if ch else 0


# ════════════════════════════════════════════════════════════
#  KEY REDEMPTION — listen in #verification-portal
# ════════════════════════════════════════════════════════════
@bot.event
async def on_message(message: discord.Message):
    if message.author.bot:
        return

    # Only process messages in #verification-portal
    if message.channel.name != Config.CHANNEL_VERIFICATION_PORTAL:
        await bot.process_commands(message)
        return

    content = message.content.strip()

    # Check if the message looks like a verification key (UUID-like format)
    if _looks_like_key(content):
        await _handle_key_redemption(message, content)
    else:
        # Delete non-key messages from uninitiated members to keep channel clean
        uninitiated_role = discord.utils.get(message.guild.roles, name=Config.ROLE_UNINITIATED)
        if uninitiated_role and uninitiated_role in message.author.roles:
            try:
                await message.delete()
            except discord.NotFound:
                pass

    await bot.process_commands(message)


def _looks_like_key(text: str) -> bool:
    """A valid key is 64 hex characters (our SHA-256 based key format)."""
    import re
    return bool(re.fullmatch(r"[0-9a-f]{64}", text.lower()))


async def _handle_key_redemption(message: discord.Message, key: str):
    guild  = message.guild
    member = message.author

    result = db.redeem_key(key, str(member.id))

    # Delete the key message immediately for security
    try:
        await message.delete()
    except discord.NotFound:
        pass

    if result["status"] == "invalid":
        await member.send(
            "**Verification Failed.**\n\n"
            "The key you submitted is invalid. Please double-check that you copied it correctly "
            "from the DM I sent you. If you believe this is an error, contact The Dark Council."
        )
        return

    if result["status"] == "expired":
        await _apply_sacrificial_lambs(guild, member)
        await member.send(
            "**Your Verification Key Has Expired.**\n\n"
            "The key you submitted is no longer valid — it expired before you could use it. "
            "As a result, you have been placed under restricted access.\n\n"
            "To try again, you must submit a new application from the beginning:\n"
            f">>> {Config.GITHUB_PAGES_URL}\n\n"
            "Do not delay this time. The Cult does not wait."
        )
        return

    if result["status"] == "already_used":
        await member.send(
            "**Key Already Redeemed.**\n\n"
            "This key has already been used. If you believe this is a mistake, "
            "contact The Dark Council immediately."
        )
        return

    if result["status"] == "wrong_user":
        await member.send(
            "**Key Mismatch.**\n\n"
            "This key was not issued to you. Attempting to use another member's key "
            "is a serious violation. This incident has been logged."
        )
        log.warning(f"Key mismatch: {member} tried to use key issued to {result.get('issued_to')}")
        await _log_security_event(guild, f"⚠️ **Key Mismatch** — {member.mention} attempted to redeem a key not issued to them.")
        return

    # ── SUCCESS — promote the member ──
    builders_eligible = result.get("builders_club", False)
    await _promote_member(guild, member, builders_eligible)

    await member.send(
        f"**You have been accepted into EVILISM, {member.display_name}.**\n\n"
        f"Your initiation is complete. The Gates of Umbra have opened for you.\n\n"
        f"You have been granted the rank of **Acolyte of Evil**. "
        f"Prove your worth, and greater ranks await.\n\n"
        + (
            f"✦ **Umbra's BuildersClub** — You have also been inducted as a Founding Member. "
            f"This honor is permanent and marks you as one of the first to walk this path.\n\n"
            if builders_eligible else ""
        )
        + f"Welcome to the Cult. Do not disappoint us.\n"
        f"— **EVILISM Verification System**"
    )

    log.info(f"Member {member} successfully verified and promoted.")
    await _log_security_event(
        guild,
        f"✅ **Verification Complete** — {member.mention} (`{member.id}`) has been accepted and promoted to Acolyte of Evil."
        + (" Inducted into Umbra's BuildersClub." if builders_eligible else "")
    )


async def _promote_member(guild: discord.Guild, member: discord.Member, builders_club: bool):
    """Remove Uninitiated, add Acolyte of Evil (and optionally BuildersClub)."""
    roles_to_remove = [Config.ROLE_UNINITIATED, Config.ROLE_SACRIFICIAL_LAMBS]
    roles_to_add    = [Config.ROLE_ACOLYTE]
    if builders_club:
        roles_to_add.append(Config.ROLE_BUILDERS_CLUB)

    for role_name in roles_to_remove:
        role = discord.utils.get(guild.roles, name=role_name)
        if role and role in member.roles:
            try:
                await member.remove_roles(role, reason="Verification complete")
            except discord.Forbidden:
                log.warning(f"Cannot remove role '{role_name}' from {member}")

    for role_name in roles_to_add:
        role = discord.utils.get(guild.roles, name=role_name)
        if role:
            try:
                await member.add_roles(role, reason="Verification complete")
            except discord.Forbidden:
                log.warning(f"Cannot add role '{role_name}' to {member}")
        else:
            log.warning(f"Role '{role_name}' not found in guild.")


async def _apply_sacrificial_lambs(guild: discord.Guild, member: discord.Member):
    """Remove Uninitiated, add Sacrificial Lambs."""
    uninitiated = discord.utils.get(guild.roles, name=Config.ROLE_UNINITIATED)
    lambs       = discord.utils.get(guild.roles, name=Config.ROLE_SACRIFICIAL_LAMBS)

    if uninitiated and uninitiated in member.roles:
        try:
            await member.remove_roles(uninitiated, reason="Key expired")
        except discord.Forbidden:
            pass

    if lambs:
        try:
            await member.add_roles(lambs, reason="Verification key expired")
        except discord.Forbidden:
            log.warning(f"Cannot assign Sacrificial Lambs to {member}")
    else:
        log.warning(f"Role '{Config.ROLE_SACRIFICIAL_LAMBS}' not found.")


async def _log_security_event(guild: discord.Guild, message: str):
    """Post to #security-logs channel."""
    channel = discord.utils.get(guild.text_channels, name=Config.CHANNEL_SECURITY_LOGS)
    if channel:
        try:
            await channel.send(message)
        except discord.Forbidden:
            log.warning("Cannot post to #security-logs — missing permissions.")
    else:
        log.warning(f"Channel '{Config.CHANNEL_SECURITY_LOGS}' not found.")


# ════════════════════════════════════════════════════════════
#  BACKGROUND TASK — check for expired forms & keys every hour
# ════════════════════════════════════════════════════════════
@tasks.loop(hours=1)
async def check_expiries():
    log.info("Running expiry check...")
    expired_forms = db.get_expired_pending_forms()
    expired_keys  = db.get_expired_keys()

    for guild in bot.guilds:
        for entry in expired_forms:
            member = guild.get_member(int(entry["discord_id"]))
            if member:
                log.info(f"Form expired for {member} — auto-denying.")
                try:
                    await member.send(
                        "**Your Application Has Expired.**\n\n"
                        "Your EVILISM initiation application was not reviewed within the 7-day window, "
                        "or it was not submitted in time. Your entry has been automatically denied.\n\n"
                        "You are welcome to begin again:\n"
                        f">>> {Config.GITHUB_PAGES_URL}\n\n"
                        "Do not let time slip away from you again."
                    )
                except discord.Forbidden:
                    pass
                db.mark_form_expired(entry["id"])

        for entry in expired_keys:
            member = guild.get_member(int(entry["discord_id"]))
            if member:
                log.info(f"Key expired for {member} — applying Sacrificial Lambs.")
                await _apply_sacrificial_lambs(guild, member)
                try:
                    await member.send(
                        "**Your Verification Key Has Expired.**\n\n"
                        "You were accepted, but you did not use your key in time. "
                        "You have been placed under restricted access.\n\n"
                        "Submit a new application to try again:\n"
                        f">>> {Config.GITHUB_PAGES_URL}"
                    )
                except discord.Forbidden:
                    pass
                db.mark_key_expired(entry["id"])
                await _log_security_event(
                    guild,
                    f"⏰ **Key Expired** — {member.mention} (`{member.id}`) did not redeem their key in time. "
                    f"Assigned Sacrificial Lambs."
                )


# ════════════════════════════════════════════════════════════
#  SLASH COMMANDS (Admin only)
# ════════════════════════════════════════════════════════════

@bot.tree.command(name="builders", description="[UMBRA only] Toggle Umbra's BuildersClub availability on the form.")
async def toggle_builders(interaction: discord.Interaction, enabled: bool):
    if str(interaction.user.id) != Config.UMBRA_DISCORD_ID:
        await interaction.response.send_message(
            "❌ Only UMBRA may control the BuildersClub toggle.", ephemeral=True
        )
        return

    db.set_builders_club(enabled)
    status = "**enabled** ✦" if enabled else "**disabled**"
    await interaction.response.send_message(
        f"Umbra's BuildersClub has been {status} on the verification form.\n"
        f"All new applicants will {'see' if enabled else 'not see'} the BuildersClub banner.",
        ephemeral=True,
    )
    log.info(f"UMBRA toggled BuildersClub: {enabled}")


@bot.tree.command(name="approve", description="[TDC/Staff] Approve a pending verification application.")
async def approve_application(interaction: discord.Interaction, discord_id: str):
    if not _is_staff(interaction.user):
        await interaction.response.send_message("❌ You do not have permission to approve applications.", ephemeral=True)
        return

    result = db.approve_application(discord_id)
    if not result:
        await interaction.response.send_message(f"❌ No pending application found for user ID `{discord_id}`.", ephemeral=True)
        return

    guild  = interaction.guild
    member = guild.get_member(int(discord_id))

    if not member:
        await interaction.response.send_message(
            f"⚠️ Application approved and key generated, but member `{discord_id}` is no longer in the server.",
            ephemeral=True,
        )
        return

    builders_eligible = db.is_builders_club_enabled() and result.get("builders_club_at_submission", False)
    key = result["key"]

    key_message = (
        f"**Your Application Has Been Accepted, {member.display_name}.**\n\n"
        f"The Dark Council has reviewed your oath and found it worthy.\n\n"
        f"Below is your **Verification Key**. Copy it exactly and paste it into the "
        f"`#verification-portal` channel in the EVILISM server to complete your initiation.\n\n"
        f"```\n{key}\n```\n"
        f"⚠️ **This key expires in 84 hours (3.5 days).** Do not delay.\n"
        f"If it expires, you will be placed under restricted access and must reapply.\n\n"
        f"*Do not share this key with anyone. It is bound to your account.*\n"
        f"— **EVILISM Verification System**"
    )

    try:
        await member.send(key_message)
        await interaction.response.send_message(
            f"✅ Application approved. Key sent to {member.mention} via DM.", ephemeral=True
        )
    except discord.Forbidden:
        await interaction.response.send_message(
            f"⚠️ Application approved but could not DM {member.mention} — they have DMs disabled.",
            ephemeral=True,
        )

    await _log_security_event(
        guild,
        f"✅ **Application Approved** — {member.mention} (`{member.id}`) approved by "
        f"{interaction.user.mention}. Key issued (expires 84h)."
    )
    log.info(f"Application approved for {member} by {interaction.user}")


@bot.tree.command(name="deny", description="[TDC/Staff] Deny a pending verification application.")
async def deny_application(interaction: discord.Interaction, discord_id: str, reason: str = "No reason provided."):
    if not _is_staff(interaction.user):
        await interaction.response.send_message("❌ You do not have permission to deny applications.", ephemeral=True)
        return

    result = db.deny_application(discord_id)
    if not result:
        await interaction.response.send_message(f"❌ No pending application found for user ID `{discord_id}`.", ephemeral=True)
        return

    guild  = interaction.guild
    member = guild.get_member(int(discord_id))

    if member:
        try:
            await member.send(
                f"**Your Application Has Been Denied, {member.display_name}.**\n\n"
                f"After careful review, The Dark Council has decided not to grant you entry at this time.\n\n"
                f"**Reason:** {reason}\n\n"
                f"You may submit a new application in the future if you believe you can better "
                f"demonstrate your dedication to the Cult.\n\n"
                f"— **EVILISM Verification System**"
            )
        except discord.Forbidden:
            pass

    await interaction.response.send_message(
        f"✅ Application denied for `{discord_id}`. Reason: {reason}", ephemeral=True
    )
    await _log_security_event(
        guild,
        f"❌ **Application Denied** — <@{discord_id}> (`{discord_id}`) denied by "
        f"{interaction.user.mention}. Reason: {reason}"
    )
    log.info(f"Application denied for {discord_id} by {interaction.user}: {reason}")


@bot.tree.command(name="pending", description="[TDC/Staff] List all pending verification applications.")
async def list_pending(interaction: discord.Interaction):
    if not _is_staff(interaction.user):
        await interaction.response.send_message("❌ You do not have permission to view pending applications.", ephemeral=True)
        return

    pending = db.get_pending_applications()
    if not pending:
        await interaction.response.send_message("📭 No pending applications at this time.", ephemeral=True)
        return

    lines = ["**Pending Verification Applications:**\n"]
    for app in pending:
        lines.append(
            f"• `{app['discord_id']}` — **{app['discord_username']}** — "
            f"Submitted: {app['submitted_at']} — Expires: {app['expires_at']}"
        )

    await interaction.response.send_message("\n".join(lines), ephemeral=True)


@bot.tree.command(name="viewapp", description="[TDC/Staff] View the full application for a user.")
async def view_application(interaction: discord.Interaction, discord_id: str):
    if not _is_staff(interaction.user):
        await interaction.response.send_message("❌ You do not have permission to view applications.", ephemeral=True)
        return

    app = db.get_application(discord_id)
    if not app:
        await interaction.response.send_message(f"❌ No application found for `{discord_id}`.", ephemeral=True)
        return

    QUESTION_LABELS = {
        "q1":  "Why do you want to join?",
        "q2":  "Describe EVILISM in your own words.",
        "q3":  "Oath of secrecy?",
        "q3b": "Reservations (if any):",
        "q4":  "What does 'evil' mean in EVILISM?",
        "q5":  "Player complaining — what do you do?",
        "q6":  "When to report a player?",
        "q7":  "Agree to Unholy Decrees?",
        "q8":  "Expected activity level?",
        "q9":  "Previous bans?",
        "q10": "Witness a member crossing the line?",
        "q11": "Your role in the Cult?",
        "q12": "Best JJS moment?",
        "q13": "Anything else to add?",
    }

    answers = app.get("answers", {})
    lines   = [
        f"**Application — {app['discord_username']}** (`{app['discord_id']}`)\n"
        f"Submitted: {app['submitted_at']} | Expires: {app['expires_at']}\n"
        f"BuildersClub at submission: {'Yes' if app.get('builders_club_at_submission') else 'No'}\n"
        f"{'─' * 40}"
    ]

    for key, label in QUESTION_LABELS.items():
        val = answers.get(key, "").strip()
        if val:
            lines.append(f"\n**{label}**\n{val}")

    full_text = "\n".join(lines)
    # Discord has a 2000 char limit per message; split if needed
    chunks = [full_text[i:i+1900] for i in range(0, len(full_text), 1900)]
    await interaction.response.send_message(chunks[0], ephemeral=True)
    for chunk in chunks[1:]:
        await interaction.followup.send(chunk, ephemeral=True)


def _is_staff(member) -> bool:
    """Returns True if the member is UMBRA or has a staff role."""
    # Handle case where member might be a User (in DMs) instead of a Member
    user_id = str(member.id)
    if user_id == Config.UMBRA_DISCORD_ID:
        return True
    
    # If it's a DM, they can't have server roles, so only UMBRA passes
    if not hasattr(member, 'roles'):
        return False
        
    staff_roles = {Config.ROLE_DARK_COUNCIL, Config.ROLE_HARBINGERS}
    return any(r.name in staff_roles for r in member.roles)


# ════════════════════════════════════════════════════════════
#  RUN
# ════════════════════════════════════════════════════════════
if __name__ == "__main__":
    bot.run(Config.BOT_TOKEN)
